spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  security:
    user:
      name: user
      password: password
